version: '3.8'

services:
  customers:
    build: ./services/customers
    ports:
      - "5001:5001"
  inventory:
    build: ./services/inventory
    ports:
      - "5002:5002"
  reviews:
    build: ./services/reviews
    ports:
      - "5003:5003"
  sales:
    build: ./services/sales
    ports:
      - "5004:5004"